import type { ToolGuide } from "@/types/guide";

const guide: ToolGuide = {
  slug: "roi-calculator",
  intro: [
    "Return on Investment, or ROI, is the single most common metric for answering one question: did this investment actually pay off, and by how much. Whether you're evaluating a stock purchase, a marketing campaign, a piece of equipment for a business, or a home renovation, ROI expresses the result as a simple percentage that's easy to compare across completely different kinds of investments.",
    "This ROI calculator is built for investors sizing up a trade after the fact, business owners judging whether a marketing spend or equipment purchase was worth it, and anyone deciding between two opportunities who wants a like-for-like number instead of just comparing raw dollar amounts. Enter what you put in and what you got back, and it calculates the ROI percentage, the net profit or loss in dollars, and, if you provide a time period, the annualized ROI.",
    "ROI is deliberately simple: it only needs two numbers, the cost of the investment and the value returned. That simplicity is also its main limitation, since it doesn't account for how long the investment took to pay off, which is exactly why this calculator includes an optional annualized ROI figure alongside the basic percentage.",
  ],
  sections: [
    {
      heading: "ROI Formula Explained With Examples",
      paragraphs: [
        "The ROI formula is: ROI = (Net Profit ÷ Cost of Investment) × 100, where Net Profit equals the Final Value minus the Initial Investment. If you put in $10,000 and it grew to $15,000, the net profit is $5,000, and the ROI is ($5,000 ÷ $10,000) × 100 = 50%. A 50% ROI means the investment returned half again as much as you put in, on top of getting your original amount back.",
        "ROI can also be negative. If that same $10,000 investment dropped to $8,000, the net profit is -$2,000, and the ROI is -20%, meaning you lost 20% of what you invested. The formula works identically whether you're evaluating a stock, a piece of real estate, a marketing campaign's revenue against its ad spend, or the resale value of a renovated property compared to what the renovation cost.",
        "A marketing example: spending $5,000 on an ad campaign that generates $8,000 in attributable revenue gives a net profit of $3,000 and an ROI of 60%. Business context matters here since \"revenue\" isn't the same as \"profit\"; a more precise marketing ROI calculation would use the profit generated by that revenue as the final value, not the raw revenue figure, if the cost of goods sold is significant.",
      ],
      bullets: [
        "ROI = (Net Profit ÷ Cost of Investment) × 100",
        "Net Profit = Final Value − Initial Investment",
        "A positive ROI means the investment gained value; a negative ROI means it lost value",
        "ROI is a ratio, so it works the same whether the numbers are in the hundreds or the millions",
      ],
    },
    {
      heading: "ROI vs ROE vs IRR vs Annualized ROI: What Each One Measures",
      paragraphs: [
        "Basic ROI, as calculated above, measures total return over the entire life of an investment regardless of how long that took, which makes it easy to calculate but hard to compare fairly across investments held for different lengths of time. A 50% ROI over 1 year and a 50% ROI over 10 years represent very different performance, even though the percentage is identical.",
        "This is where annualized ROI comes in, which this calculator provides when you enter a time period in years. It answers \"what steady yearly growth rate would produce this same total return,\" using the formula: Annualized ROI = ((Final Value ÷ Initial Investment)^(1/years) − 1) × 100. For the earlier $10,000 to $15,000 example held over 3 years, that's ((15000/10000)^(1/3) − 1) × 100 ≈ 14.47% per year, a more useful number for comparing against, say, a savings account's annual interest rate.",
        "Two related metrics this calculator does not compute are ROE (Return on Equity), which measures a company's profit relative to shareholder equity specifically, and IRR (Internal Rate of Return), which accounts for the timing of multiple cash flows in and out of an investment, not just a single starting and ending value. For a simple one-time investment with one exit, ROI and annualized ROI capture the picture well; for investments with periodic contributions or withdrawals, IRR is the more accurate tool.",
      ],
    },
    {
      heading: "What Counts as a Good ROI",
      paragraphs: [
        "\"Good\" ROI depends entirely on the type of investment and the time period involved. The US stock market has historically averaged around 10% annually over long periods, so a diversified stock investment producing an annualized ROI meaningfully below that is underperforming a simple index fund. Businesses generally aim higher, often targeting 15-20% or more annualized ROI on operational investments like equipment or marketing, since business investments carry more risk and effort than passively holding stocks.",
        "Context also matters within a single asset class. A house flip might target 20%+ ROI over a single year to justify the risk and labor involved, while a long-term rental property might be considered successful at a lower annual ROI if it also generates steady rental income alongside appreciation. There's no universal threshold; the right comparison is always against the next-best alternative use of that same money.",
      ],
    },
    {
      heading: "Comparing Two Investments Using ROI",
      paragraphs: [
        "To compare two investment opportunities fairly, calculate each one's ROI (and annualized ROI, if the holding periods differ) separately using this tool, then compare the resulting percentages side by side rather than comparing the raw dollar profits. A $50,000 investment that returns $10,000 in profit (20% ROI) and a $5,000 investment that returns $2,000 in profit (40% ROI) show that the smaller investment was actually more efficient with the capital used, even though its dollar profit is smaller.",
        "This distinction matters most when capital is limited. If you only have $5,000 to invest, the ROI percentage tells you which option makes better use of that specific amount; the larger investment's higher total profit is only relevant if you actually have that much capital available to deploy in the first place.",
      ],
    },
    {
      heading: "Limitations of ROI as a Metric",
      paragraphs: [
        "ROI treats every dollar of profit the same regardless of when it arrived, which is exactly why the annualized version exists, and it doesn't factor in risk at all. Two investments with an identical 20% ROI are not equally good if one was a government bond and the other was a speculative startup investment; the volatility and chance of loss along the way matter, and ROI alone doesn't capture that.",
        "ROI also doesn't account for inflation. A 20% ROI over 5 years sounds solid, but if inflation ran at 4% annually over that period, roughly 22% of that nominal return was needed just to maintain purchasing power, so the real, inflation-adjusted return is smaller than the headline number suggests. For long holding periods, it's worth mentally discounting the ROI figure by the inflation rate over that time to get a clearer picture of actual gained value.",
      ],
    },
  ],
  useCases: [
    { title: "Evaluating a Stock or Fund Investment", description: "Enter the purchase price and current or sale value to see the total ROI and, with the holding period, the annualized return to compare against market benchmarks." },
    { title: "Judging a Marketing Campaign", description: "Compare ad spend against attributable revenue or profit to see whether a campaign's return justified the budget before repeating or scaling it." },
    { title: "Assessing a Business Equipment Purchase", description: "Compare the cost of new equipment against the added revenue or cost savings it produces to decide if the purchase paid for itself." },
    { title: "Reviewing a Home Renovation or Flip", description: "Compare renovation costs against the increase in resale value to see whether the project was financially worthwhile." },
    { title: "Comparing Two Investment Options", description: "Calculate ROI separately for two opportunities with different amounts or time periods to see which one used capital more efficiently." },
    { title: "Reporting Investment Performance", description: "Convert raw investment figures into a clean percentage return that's easier to communicate to stakeholders, clients, or partners." },
  ],
  mistakes: [
    { title: "Comparing dollar profit instead of percentage ROI", description: "A larger investment can produce a bigger dollar profit while still being a worse use of capital than a smaller investment with a higher ROI percentage." },
    { title: "Ignoring the time period when comparing ROIs", description: "A 30% ROI over 1 year is far better than a 30% ROI over 5 years; the annualized ROI figure, not the raw total, is what makes different holding periods comparable." },
    { title: "Using revenue instead of profit as the final value", description: "For business investments like marketing, using total revenue rather than profit after costs overstates the true return, since it ignores the cost of goods or services sold." },
    { title: "Not adjusting for inflation over long periods", description: "A nominal ROI over many years overstates real gains once inflation is factored in, especially for holding periods of a decade or more." },
    { title: "Treating ROI as a complete risk assessment", description: "ROI measures return only; it says nothing about how much risk or volatility was involved in achieving that return." },
  ],
  tips: [
    "Always compare investments by ROI percentage, not raw dollar profit, when deciding how to allocate limited capital.",
    "Enter the time period whenever you can, since annualized ROI is the only fair way to compare investments held for different lengths of time.",
    "For business ROI, use profit rather than revenue as the final value whenever the cost of goods or services is significant.",
    "Mentally discount a long-term ROI by the inflation rate over that period to estimate the real, purchasing-power-adjusted return.",
    "Use ROI alongside a risk assessment, not instead of one, since two investments with equal ROI can carry very different levels of risk.",
    "For investments with multiple cash inflows or outflows over time, look into IRR instead, since basic ROI assumes a single starting and ending value.",
  ],
  glossary: [
    { title: "Net Profit", description: "The final value of an investment minus its initial cost; a positive net profit means a gain, a negative one means a loss." },
    { title: "Annualized ROI", description: "The ROI expressed as an equivalent steady yearly growth rate, calculated from the total return and the number of years held, allowing fair comparison across different holding periods." },
    { title: "ROE (Return on Equity)", description: "A profitability metric that measures a company's net income relative to shareholder equity, distinct from ROI, which measures return relative to the cost of a specific investment." },
    { title: "IRR (Internal Rate of Return)", description: "A metric that calculates the annualized return of an investment accounting for the timing and size of multiple cash flows, used when an investment has more than one contribution or withdrawal." },
    { title: "CAGR (Compound Annual Growth Rate)", description: "A measure of an investment's mean annual growth rate over a period longer than one year, calculated the same way as this tool's annualized ROI." },
  ],
};

export default guide;
